# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

modLoaderVersionRange=[1,)

modMinecraftVersion=1.20.6
modMinecraftVersionRange=[1.20.6]

modVersion=1.11.0

# Versions: https://projects.neoforged.net/neoforged/neoforge
modNeoForgeVersion=20.6.138
modNeoForgeVersionRange=[20.6.138,)

# Versions: https://parchmentmc.org/docs/getting-started
modMinecraftMappingsVersion=2024.06.16
