modLoader="javafml"
loaderVersion="${modLoaderVersionRange}"
issueTrackerURL="https://github.com/Exidex/SwingThroughGrass/issues"
license="MIT"

[[mods]]
modId="swingthroughgrass"
version="${modMinecraftVersion}-${modVersion}"
displayName="SwingThroughGrass"
displayURL="https://minecraft.curseforge.com/projects/swingthroughgrass"
logoFile="logo.png"
credits="Direwolf20, Darkosto"
authors="Exidex"
description='''Don't let the grass be between you and your prey!'''

[[dependencies.swingthroughgrass]]
    modId="neoforge"
    type="required"
    versionRange="${modNeoForgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.swingthroughgrass]]
    modId="minecraft"
    type="required"
    versionRange="${modMinecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
